### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by noynek** [google-map-react/google-map-react#1102]
I apologize if this is the wrong place for the issue, but I'm trying to upgrade to React 18 and running into issues with this library. I can see in package.json it's looking for React 16 or 17 so I'm curious if there are any plans to support 18. Thanks

**Comment by karolisg** [comment]
Any ETA when fix will be merged?

**Comment by sud977** [comment]
i think more dev work will require to support react 18. One thing that I ran into after I updated to react 18 and used the createRoot instead of render method in my project was the map markers were flickering while panning through the map. The reason is with react 18, the state updates are batched, React groups multiple state updates into a single re-render for better performance. [https://codesandbox.io/s/googlemapreact-demo-forked-5gdsib](https://codesandbox.io/s/googlemapreact-demo-forked-5gdsib)

I was on a tight deadline at work so I only changed this part of the code on my fork. 
` _onChangeHandler = () => {
    if (!this.dimensionsCache_) {
      return;
    }

    const prevChildCount = (this.state.children || []).length;
    const state = this._getState();

   // added flushsync to opt-out of automatic batching
    ReactDOM.flushSync(() => {
      this.setState(
        state,
        () =>
          (state.children || []).length !== prevChildCount &&
          this._onMouseChangeHandler()
      );
    });
  };`
  
This is clearly not a proper way to do this because the _onChangeHandler is called inside lifecycle method, causing it to throw this error, "Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task." Does anyone have an idea of how to implement this properly?

**Comment by jacobgad** [comment]
Is react 18 support being worked on currently?

**Comment by aindriu80** [comment]
I'm having the same trouble, google-map-react is not working with React version 18.  It's a bit awkward to go back to React version 17,

**Comment by Manne010** [comment]
am also facing same problem any solution?

**Comment by aindriu80** [comment]
only solution is to use React version 17 but you need to edit all dependencies (react and react-dom etc ) in package.json to match 17, also the index.js file is different in version 18, you would have to change that back as well.

**Comment by dryan-FF** [comment]
hi! our team is also facing the same issue. can this PR please get approval & merge? https://github.com/google-map-react/google-map-react/pull/1103

**Comment by mayilss** [comment]
check the link below, it is for newer versions of react. to be precise v16.6 or later

https://www.npmjs.com/package/@react-google-maps/api

**Comment by MomoRazor** [comment]
Just dropping a line because as of yet React 18 is still not supported, so I'm not sure if there is some form of alternative.

**Comment by Gladys-Luke** [comment]
I am here to check if there's yet a new version that supports React v18

**Comment by XLG123** [comment]
Hi, I've been having issues with the markers that when I'm zooming in/out on the map, the markers changed their positions. It only happened on React v18, i tried doing it on React v16 and they worked fine.
