### ISSUE TITLE
Maps cooperative gesture handling

### ISSUE THREAD

**Issue by zeeke** [google-map-react/google-map-react#297]
Hi,

The cooperative gesture handling described at [this link in the documentation](https://developers.google.com/maps/documentation/javascript/interaction) is not working due to the iPad fix in #233

```js
  // src/google_map.js:867

 _onTouchMove = (event) => {
    if (this.refs.google_map_dom) {
      const mapDom = ReactDOM.findDOMNode(this.refs.google_map_dom);
      if (mapDom.contains(event.target)) {
        event.preventDefault();
      }
    }
  }	
```

I don't know how it would be on iPad without this fix. At the moment, scolling with a single finger on the map makes a warning appear but the page does not scroll. With a big map there is a chance that the user fall in a section where he can't scroll away.

I can work on a PR if some support.

**Comment by istarkov** [comment]
May be just check options on gestureHandling options, and depending on it just make off code section above. I cant help much here as have near zero knowledge about web on mobile. So feel free to provide a PR, will help if any questions I know the answer

**Comment by zeeke** [comment]
I tried googling about maps and iPad issues but I find nothing.

@jooj123 can you give a feedback about the documentation i linked above?

**Comment by jooj123** [comment]
@zeeke 

The ipad fix I added here: https://github.com/istarkov/google-map-react/pull/233
Prevents the whole page from being dragged on an ipad.
Without it the user experience is horrible on ipad.

Instead of doing this with `touchmove` events in react - it could possibly be done with "Scrolling and Panning" settings  (`greedy` option) with google maps.

But this will need to be tested - I have not checked if this prevents whats mentioned in https://github.com/istarkov/google-map-react/pull/233

**Comment by yoadsn** [comment]
@zeeke I can see that you have forked this repo and reverted the PR for #233.
I tried the same locally and that indeed solves the problem.
@jooj123 @istarkov I think this change should be put behind a flag to be an opt-in. The reason is that google maps has it's own (complex) way of handling the duality of swipe over a map (scroll page? pan map?) with the `gestureHandling` option.

The only reason I'm not 100% sure this feature can be removed completely is due to handling of the rendered markers/layers on top of the gmaps. Perhaps this has no way of working with the `gestureHandling` feature - but currently it's really destroying this lib for any touch enabled use.

**Comment by istarkov** [comment]
Lets remove, @yoadsn can you check that greedy option? Ill accept a PR with removal :-) but dont like the flag idea

**Comment by yoadsn** [comment]
@istarkov Sound good. I will wait to get last input from @jooj123 on this to make sure I am missing nothing.
Basically, what we want to say is that whenever a user of this component want to control the behavior of swipes on the map he should follow the google maps guidelines and options. (I would update the docs a little as well to make sure it's not missed).

@istarkov locally - the `gestureHandling` option of google map works great for me in the use cases I have. The setting to use to replicate #233 is indeed to use the `greedy` option.

**greedy**
![greedy](https://cloud.githubusercontent.com/assets/1684709/23758915/e410d22a-04f3-11e7-98a8-eb990215b5aa.gif)

**auto** With a scrollable container
![auto](https://cloud.githubusercontent.com/assets/1684709/23759029/2f70317a-04f4-11e7-867f-94f62a08e911.gif)

**Comment by itsmichaeldiego** [comment]
@yoadsn I am guessing this was handled in PR #334 and this issue was never closed. Let me know if otherwise and we can re-open it.

**Comment by jooj123** [comment]
So is this defaulting to `greedy` now ?

**Comment by itsmichaeldiego** [comment]
@jooj123 No, you need to set `gestureHandling: 'greedy` as detailed in #334
