### ISSUE TITLE
Adding pin on google maps site

### ISSUE THREAD

**Issue by mollynordh** [google-map-react/google-map-react#480]
I'm wondering if there's any way that the pin on the maps component also can be added on the same position on the google maps site if a user presses on the Google logo in the left hand corner of the map? I have searched the issues and read the documentations but cant find an answer.

**Comment by mistaguy** [comment]
Your question is not quite clear

**Comment by itsmichaeldiego** [comment]
@mollynordh It is related to the way our library works, we're rendering actual React components instead of google markers, we should totally take a look at this, although is not high-priority I believe it is a nice-to-have. Would you be kind to share a snippet if you find a workaround?

@mistaguy What she means is the following:

- Go to your map, lets say you have 5 markers.
- Click on the Google logo -> redirects to Google maps site.
- Load Google maps site

Expected behavior:
- Markers are shown

Actual behavior: 
- Markers are not shown

**Comment by mollynordh** [comment]
Thank you @itsmichaeldiego. Will absolutely share a snippet if I find a workaround!

**Comment by itsmichaeldiego** [comment]
@mollynordh I think an approach would be creating the markers via google API based on the positions of our marker's component. That way if you open google maps will show your markers. If this feature is really something you need.

**Comment by itsmichaeldiego** [comment]
Hey @stephenfarrar, sorry to bother you with this, but wondering if you've an input on this end.

**Comment by stephenfarrar** [comment]
This would have to be a new feature in the Maps API.

You could submit a feature request:
https://developers.google.com/maps/documentation/javascript/support#issue-tracker

**Comment by itsmichaeldiego** [comment]
@stephenfarrar But, this is a feature Google Map already has, as long as you've proper Google Markers defined in your map, when you click in the Google button, the maps.google.com page will show them. I think the problem is that given we don't have google markers but react components, its not shown as its supposed to. 🤔

**Comment by sators** [comment]
I am in the same boat as @mollynordh - looking for the markers and polylines placed on the map to be seen on maps.google.com when the user clicks on the "Google" logo.

Even if I use the Google Maps API for placing native Google markers on the map, clicking the logo still does not display markers on maps.google.com.

However, looking at Google's own sample Map API code, their [simple Markers demo](https://developers.google.com/maps/documentation/javascript/examples/marker-simple) does not display the marker on maps.google.com when you click the Google logo...even the tooltip on the Google logo states "Open this _area_ in Google Maps"

Further reading, this question has been asked of the core Google Maps API on [stackoverflow](https://stackoverflow.com/questions/48299689/open-generated-map-with-markers-in-google-maps) as well, with no luck...

**Comment by itsmichaeldiego** [comment]
@sators Great research, that means this issue is with Google Maps API itself and not with the library. 
I think it makes sense, as Google logo doesn't hold the info in the params linking to google.maps.com, and probably the Markers are shown when your MAP_KEY is associated to those markers too.
