### ISSUE TITLE
Map zoom causes markers to pop

### ISSUE THREAD

**Issue by falconmick** [google-map-react/google-map-react#608]
I have attempted to find this issue via looking over all open issues, however I am unable to find it. If this issue is already open and I am blind, feel free to point me there and close this.

When I zoom in, my marker pops to either the top left or bottom right before correcting itself, however on occasion it looks like it actually sticks the the map correctly? However this could be just due to the zoom level and some luck.

this can be seen on your demo: http://google-map-react.github.io/google-map-react/map/main/

zoom in fairly close to a price, then zoom in/out. You will notice that the marker jumps to one of those corners before fixing itself. Is it not possible to ahead of time calculate the new position it will be pinned to and lerp it there OR just don't move the marker inside of the map view until the new co-ordinate is found and then interpolate it to that position over .2 seconds?

Cheers,
Michael.

**Comment by jabidof** [comment]
Hi
Could it be related to the google map api version you use?
There was such an issue a few months ago.
Which version are you using?

**Comment by itsmichaeldiego** [comment]
Hey @falconmick! I am sorry you did not try updating the library first, it would have save you some time. Current version of `google-map-react` is `1.0.5`, please upgrade and the problem will disappear, we handled this in #510 as @jabidof perfectly pointed out.

The problem can be seen in the demo because the demo isn't updated, sorry for that.

**Comment by falconmick** [comment]
1. I should have tried updating first, that was stupid
2. holy moly! When did we tick over to v1.0.0! congrats all!

**Comment by itsmichaeldiego** [comment]
1. No problem mate, that is what we're here for. 😄❤️ 
2. Thank you! I bumped to `1.0.0` when we changed the way we draw the markers in #510, I thought it was a major change and being at `0.x.x` seemed like very low for a library so popular and used.

@falconmick Glad to see you're still using our library, let me know if you want to help out! Otherwise if you have any problem don't hesitate on creating an issue again, good luck!
