### ISSUE TITLE
How to make a moving marker like Uber cars?

### ISSUE THREAD

**Issue by celerateapp** [google-map-react/google-map-react#619]
I create a marker like this:
`<GoogleMapReact
     bootstrapURLKeys={{ key: GOOGLE_MAP_API_KEY }}
     center={this.props.center}
     zoom={this.props.zoom}
     options={createMapOptions}>
      <Marker
           lat={lat}
	   lng={lng}
	   marker_img={IMG} />
  </GoogleMapReact>`

Now how do I move this marker like a car on location updates?
I use states to update position of the marker but it doesn't animate. How do I do this?

**Comment by johnhult** [comment]
This really should be asked on StackOverflow.

I think the issue might be:
React components doesn't re-render unless it's a state or props items that gets updated. So that might be the only issue you have.

Nevertheless, here is how I've done it:

`
watchUserPos = () => {
		if (navigator.geolocation) {
			navigator.geolocation.watchPosition(
				position => {
					this.setState({
						userPos: {
							lat: position.coords.latitude,
							lng: position.coords.longitude
						}
					});
				},
				() => {
					this.setState({
						userError: 'omg we got an error: ' + error
					});
				},
				{
					enableHighAccuracy: true,
					timeout: 60000
				}
			);
		}
		else {
			this.setState({
				error: ERROR.noGeoLocation
			});
		}
	};
`

Then I just pass down this.state.userPos to my map component. Then I have a component inside the maps component:

`
{this.props.userPos && !this.props.userError ? (
						<Marker
							className="User"
							key="user"
							lat={this.props.userPos.lat}
							lng={this.props.userPos.lng}
						/>
					) : null}
`

That is all I needed for position.

**Comment by celerateapp** [comment]
It updates. I don't have a problem with location updation. My issue is when a latlng is updated the marker jumps from one place to another but I want it to move like a car. Have you ever tracked an Uber ride on the web? something like that.  Also sorry for not posting in on Stack, found this better. Thank you.
![moving_car](https://user-images.githubusercontent.com/35843795/43647359-09e6a6ec-9755-11e8-840b-bde191758b0b.gif)

**Comment by johnhult** [comment]
Ah. Well, I'd say you'd need to save a couple of positions and animate the car between the points. Once again, something that should probably be asked on Stack Overflow.

But I would probably use an array of values, previous and new, and calculate some delta angle between the values and animate the car on top with correct angle between the points. So everytime you get a new point you start animating towards that point rather than just showing that point.

Another way I suppose would be to use some sort of native function for getting direction and calculate the angle based on that but I don't think you'd get the same smooth animation then.

**Comment by itsmichaeldiego** [comment]
@celerateapp Hey, thanks for using our library. As @johnhult said, this is not related to the library itself. So I need to close the issue, but I will be happy to help if you provide a live code example where I can check what do you want to achieve.
