### ISSUE TITLE
Maps API broken

### ISSUE THREAD

**Issue by jadonald-s1** [google-map-react/google-map-react#635]
The API no longers works because of changes to Google's new maps api usage policy.  Is this going to be fixed?

**Comment by jadonald-s1** [comment]
Now just see warning from google saying it can load.  I know it's because the api key that was being used has probably reached it's usability limit.

**Comment by 3llen** [comment]
when i open the [example page](http://google-map-react.github.io/google-map-react/map/simple), there is a popup from google "impossible to load google map on this page"

**Comment by ntregillus** [comment]
yeah, for the life of me i cannot find where I can set the google api key value.....

**Comment by itsmichaeldiego** [comment]
@ntregillus @3llen @jadonald-s1 @jabidof In order to say that the api is not working, you must provide a not-working example. [Here is a working example](https://codesandbox.io/s/j7r9mz4nx9). And on my end its working perfectly.

Of course if you don't use the key it will show the developer mode.

@ntregillus You've to use the key inside the attribute `bootstrapURLKeys` as [described in the api documentation](https://github.com/google-map-react/google-map-react/blob/master/API.md#bootstrapurlkeys-object) and also in the [main example](https://github.com/google-map-react/google-map-react#getting-started)

Until seeing a non-working example, I have to close this issue.
