### ISSUE TITLE
onChange function returning lng greater than 180

### ISSUE THREAD

**Issue by tbaustin** [google-map-react/google-map-react#718]
Not sure why, but I am getting longitudes that are greater than 180 on my onchange function which should not be possible.

These are the bounds being passed. The onchange function is being called when the center state is being changed and this is when that happens. 
<img width="433" alt="screen shot 2019-02-13 at 4 57 39 pm" src="https://user-images.githubusercontent.com/14001400/52749999-885c2300-2fb0-11e9-864c-9c0039cca65c.png">

**Comment by itsmichaeldiego** [comment]
@tbaustin I work with a project that has the same approach and we don't face that problem, which makes me thing it might be on your data? 

Your last longitude seems to work for me in [latlong.net](https://www.latlong.net/Show-Latitude-Longitude.html):

![screen shot 2019-02-13 at 8 55 57 pm](https://user-images.githubusercontent.com/6419886/52752510-ddf4f780-2fd1-11e9-9bdc-e96f60d106da.png)

**Comment by tbaustin** [comment]
Yes but if I pass a center into the center prop of the map the on change should reflect that

**Comment by tbaustin** [comment]
<img width="731" alt="screen shot 2019-02-14 at 8 01 54 am" src="https://user-images.githubusercontent.com/14001400/52791595-edeef480-302e-11e9-92fb-84b8b4bc591b.png">

The center state is what is causing the onchange to call. As you can see something is going wrong.

**Comment by wmtpratikk** [comment]
@tbaustin 
I'm also facing the same issue. is there any solution for this ?

**Comment by blaiz** [comment]
I'm having the exact same issue and it's breaking some of our logic because `271` is not a valid longitude.

>Your last longitude seems to work for me in latlong.net:

It doesn't work for me on the same website:
![Screen Shot 2021-03-03 at 2 18 08 PM](https://user-images.githubusercontent.com/1617767/109880099-5c5d7a00-7c2b-11eb-822a-25765455d63a.png)
![Screen Shot 2021-03-03 at 2 18 13 PM](https://user-images.githubusercontent.com/1617767/109880104-5d8ea700-7c2b-11eb-89de-2eff7ba6eaed.png)

Maybe the website changed?

In any case, clearly `271` longitude is an invalid longitude. If you try it in Google Maps, it doesn't work either. When you pan the map on the Google Maps website, once the value reaches -180 longitude the value becomes 180 longitude. Why isn't this library behaving the same way? Is this library just a wrapper around the Google Maps API or is it doing some extra logic? 

What's funny is that with this library if you keep panning the map, it will go to 300, 400, 500, 800, etc. longitude. It keeps going up. IMO, this is undesired behavior.

**Comment by arsalanfardi** [comment]
I was also experiencing this issue and needed accurate longitudes so that I could query a database of user locations. It seems that the library was not wrapping longitudes resulting in values greater than 180. Although you could still derive the correct longitude, what I found to be a more formidable approach was to to get bounds directly through the Google Maps API. I got access to the API through the onGoogleApiLoaded property and saved it in the state of my component:

`
  const handleGoogleApiLoad = (maps: { map: google.maps.Map }) => {
    setMapsApi(maps.map);
    const bounds = getMapBounds(maps.map.getBounds());
    dispatch(setMapBounds(bounds));
  };

  const handleMapChange = (value: ChangeEventValue) => {
    // Capture change in center position and bounds when the map is moved
    setCenter(value.center);
    const bounds = getMapBounds(mapsApi?.getBounds());
    dispatch(setMapBounds(bounds));
  };

  return (
    <div className={styles.map}>
      <GoogleMapReact
        onGoogleApiLoaded={handleGoogleApiLoad}
        onChange={handleMapChange}
        defaultZoom={zoom}
        center={center}
        options={defaultMapOptions}
      ></GoogleMapReact>
    </div>
  );
`

`getBounds()` returns a `LatLngBounds` object which you can use to get the SW and NE boundaries.
