### ISSUE TITLE
Marker repositions when zoomed

### ISSUE THREAD

**Issue by petter-kaspersen** [google-map-react/google-map-react#771]
Hey!

I'm having an issue where the markers change position when I zoom out/in on the map.

Using latest version of google-map-react and no additional libs that interefer with the map.

**Comment by schroerbrian** [comment]
I had the same issue and was able to solve it by adding the recommended CSS to the `.marker` class as described in this thread: https://github.com/google-map-react/google-map-react/issues/771

**Comment by pawelotto** [comment]
No solutions described in any of these issues helped and my markers are still floating freely on the map while zooming in/out. This makes this module virtually unusuable.

**Comment by pawelotto** [comment]
@petter-kaspersen After some trial and error I figured out what's the problem! The _floating_ of markers is caused by the fact that they are lat/lng coordinatates are _centered_ to the **upper left corner**  of the marker, so the larger the marker component is the farther away it will flow from the coordinates centre. 
This effect can be clearly seen on large markers whereas it doesn't show on a marker that is only one pixel in height/width because the centre of the marker equals on the upper left corner.
The solution to this is to offset the marker in CSS so that marker centre equals lat/lng coordinates.

I hope this helps.
Cheers.

**Comment by borm** [comment]
don`t forgot about 
```
transform: 'translateZ(0) translate(-50%, -50%)',
backfaceVisibility: 'hidden',
```
