### ISSUE TITLE
Possible to pass className prop to GoogleMap component?

### ISSUE THREAD

**Issue by intensr** [google-map-react/google-map-react#815]
Hey cool project,
I just wanted to ask if it would be possible to add the `className` prop to the GoogleMap main component to make it usable for libraries such as e.g. styled components or/and emotion.

**Comment by itsmichaeldiego** [comment]
@intensr What exactly do you need to do?

**Comment by intensr** [comment]
```import GoogleMapReact from 'google-map-react';

**Comment by intensr** [comment]
```
import GoogleMapReact from 'google-map-react';
export const Map = styled(GoogleMapReact)({
  color: 'blue',
  background: 'red'
});
```
You can do things as such to style components. Thats very common and popular due to libraries such as emotion or styled components. They use the className prop for such. So if you could pass it down it would help people who write react projects in such manner. Also people who would like to style the map container via classnames.

**Comment by intensr** [comment]
?

**Comment by itsmichaeldiego** [comment]
@intensr That is really not necessary, because you do need a wrapper always for the Google Map React component, as you need for google maps, so you can just style the container like we do in [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples/blob/master/src/components/GoogleMap.js#L6)
