### ISSUE TITLE
Please Add Marker.setPosition() method in order to set position.

### ISSUE THREAD

**Issue by aryan-smartsense** [google-map-react/google-map-react#817]
if this library will have the support for setPosition method then we don't have to re-render each and every marker everytime one of the marker location changes instead we can just use the marker.setPosition Method instead....

**Comment by neerajkrbansal1996** [comment]
Yupp! this feature would have been really helpful........

**Comment by beeeku** [comment]
Super useful feature! Currently, if we change the state of the marker continuously due to the rerender of each marker block the UI loop and map become unuseful.

**Comment by dave4jr** [comment]
Not sure if this will help you, but I was having issues with this as well and had to use React.PureComponent and it solved all the additional re-renders.

**Comment by beeeku** [comment]
@dave4jr That's interesting! Can you show an example of how did you achieve this? It will be helpful to a lot of us.

**Comment by itsmichaeldiego** [comment]
Nowadays you can use [pure functional components](https://blog.logrocket.com/pure-functional-components-in-react-16-6/) to fix this! But yeah if you're using older versions of React, as @dave4jr said, you can fix this with a [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent). 

This is more an issue with how we use React / JS instead of the library itself
