### ISSUE TITLE
Marker location isn't correct

### ISSUE THREAD

**Issue by voxvici** [google-map-react/google-map-react#844]
1. Fetch https://maps.googleapis.com/maps/api/geocode/json?address=Miami&sensor=false&key=YOURAPIKEY
Or use Lat: 25.7616798 and Lng: -80.1917902

2. Create GoogleMapReact

3. Add Marker with Lat and Lng above

4. See difference between where Miami location and Marker location

![bug](https://user-images.githubusercontent.com/57754475/76161483-0aa21280-60f1-11ea-839a-75f5f7c86a42.png)

![correct](https://user-images.githubusercontent.com/57754475/76161508-4f2dae00-60f1-11ea-9d10-ebfb83e240dc.png)

**Comment by voxvici** [comment]
Anyone have similar issue?

**Comment by promentol** [comment]
@voxvici I have similiar issue, how did you resolve it?

**Comment by itsmichaeldiego** [comment]
@promentol @voxvici Seems that your issue is that you want your Marker to be positioned `bottom center`, by default in Google maps we position it in `top left`, for that you need yo change the marker's position.

[You can find more about this in the docs](https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker)

Probably you should do something like:

`
const markerStyles = {
  position: 'absolute',
  transform: 'translate(-50%, 0)'
}

const Marker = () => (
  <div style={markerStyles}>
    {this.props.text}
  </div>
);
`
