### ISSUE TITLE
Can't call setState on a component that is not yet mounted. This is a no-op

### ISSUE THREAD

**Issue by nakedelement-gb** [google-map-react/google-map-react#867]
I have the same issue as [here](https://github.com/google-map-react/google-map-react/issues/565).

When I initialise the map, I get an error in the console:

"Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the GoogleMapMarkers component."

This is my code:

```
export default function SingleLocationMap(props) {
    return props.lat && props.lng ? (
        <div style={{ height: '300px', width: '100%' }}>
            <GoogleMapReact
                bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_API_KEY }}
                defaultCenter={{
                    lat: props.lat,
                    lng: props.lng,
                }}
                defaultZoom={18}
            ></GoogleMapReact>
        </div>
    ) : (
        <></>
    );
}
```

The values of lat and lng are loaded from an API, so are not assigned when the component is constructed. Clearly I'm expecting there to be no error.

![image](https://user-images.githubusercontent.com/59641414/82155483-2baf7e00-986d-11ea-97fb-f1d8e6dcd1d5.png)

**Environment:**

 - OS: Linux Mint
 - Browser Chrome
 - Version 1.1.7

**Comment by carlosrodrigues94** [comment]
I have the same issue on mac, using Firefox, Chrome and Edge, they said that was a error on my code but no one have a solution.

**Comment by Amstrong** [comment]
I have the same issue on Mac in Chrome.

**Comment by anfehernandez94** [comment]
Same error on Windows 10 in Chrome

**Comment by Amstrong** [comment]
@anfehernandez94 I recommend using another library as this one has bugs. Actually in using  ["@react-google-maps/api"](https://github.com/JustFly1984/react-google-maps-api)  this solved for me. Have a nice Documentation! 👍

**Comment by NhaPCS** [comment]
I got same issue then I added `defaultZoom` and `defaultCenter`, it works

**Comment by itsmichaeldiego** [comment]
Hey everyone, thanks for sharing your issues.

It seems that this is just a warning, not a *bug*, as it does not prevent the library from working.
It also seems that this is an issue with the way you're using JS and not the library itself.

I think the problem is that first, you conditionally render the map, and second the map is not being rendered in a class or a pure-function component, it is just a function, so instead of your code, you should do something like:

```javascript
const ParentComponent = (props) => {
  <div>
     {props.lat && props.lng && (
        <MapComponent {...props} />
     )}
  </div>
}

const MapComponent = (props) => {
    return (
        <div style={{ height: '300px', width: '100%' }}>
            <GoogleMapReact
                bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_API_KEY }}
                defaultCenter={{
                    lat: props.lat,
                    lng: props.lng,
                }}
                defaultZoom={18}
            />
        </div>
    ) 
```

Hope that helps everyone!

**Comment by itsmichaeldiego** [comment]
Hey everyone, thanks for sharing your issues.

It seems that this is just a warning, not a *bug*, as it does not prevent the library from working.
It also seems that this is an issue with the way you're using JS and not the library itself.

I think the problem is that first, you conditionally render the map, and second the map is not being rendered in a class or a pure-function component, it is just a function, so instead of your code, you should do something like:

```javascript
const ParentComponent = (props) => {
  <div>
    {props.lat && props.lng && (
      <MapComponent {...props} />
    )}
  </div>
}

const MapComponent = (props) => {
  return (
    <div style={{ height: '300px', width: '100%' }}>
      <GoogleMapReact
        bootstrapURLKeys={{ 
          key: process.env.REACT_APP_GOOGLE_API_KEY 
        }}
        defaultCenter={{
          lat: props.lat,
          lng: props.lng,
        }}
        defaultZoom={18}
      />
    </div>
  )
}
```

Let me know if that helps @NhaPCS @anfehernandez94 @Amstrong @carlosrodrigues94 @nakedelement-gb

**Comment by itsmichaeldiego** [comment]
I am closing the issue as I can't help further without a live example, if you provide me with one I am happy to help you all out.
