### ISSUE TITLE
Component container for markers?

### ISSUE THREAD

**Issue by jmaltis** [google-map-react/google-map-react#892]
Hi there,

I was trying to figure out a way to wrap my markers in a Component, instead of having to add each individual marker components as direct children of `GoogleMapReact`.

Basically reaching something like:
```
<GoogleMapReact ...>
    <MarkersWrapper/>
</GoogleMapReact>
```
where 
```
const MarkersWrapper = () => {
    // Some logic here
    // ...

    return markers.map(marker => <Marker lat={marker.lat} lng={marker.lng}... />);
}
```

I need that for different reasons, but mostly to encapsulate some logic in the MarkersWrapper component (I actually don't event need an HTML tag of any sort to wrap the markers, returning an array directly is fine to me).
The issue is, since this direct child (MarkersWrapper) of GoogleMapReact doesn't have any lat/lng properties, it renders all my "internal" markers right in the middle on the map, not taking into consideration their own lat/lng.

One solution I found is to use the "constructor" syntax instead of the "component syntax" and going with:
```
<GoogleMapReact ...>
    {MarkersWrapper()}
</GoogleMapReact>
```
But that solution prevents me from having a local state in the MarkersWrapper, which was originally the goal...

I feel like I have gone full circle here, any help would be greatly appreciated.
Thank you very much

**Comment by itsmichaeldiego** [comment]
@jmaltis I think your problem is more on how to use React than with the library, therefore I need to close the issue.

I can tell you that what you're trying to do can be achieved in many ways, first, you already have a MarkersWrapper, it is the component where you render `GoogleMapReact`, there you can pass all the logic you want:

```javascript
const Wrapper = () => {
    // Some logic here
    // ...

    return (
      <GoogleMapReact ...>
        {markers.map(marker => <Marker lat={marker.lat} lng={marker.lng}... />);}
      </GoogleMapReact>
   )
}
```

**Comment by wolasss** [comment]
Hey, thanks for the library, it works pretty well. I would like to comment on this issue though cause I ran into the same problem, that the children with lat,lng position must be direct children of `GoogleMapReact` component. 

I think being able to wrap the markers in some other react component would be very useful. Consider such scenario: 

You have many markers, that are grouped by some logic. Consider group of markers as a layer. Each layer has to be fetched separately and may involve additional logic to render the markers that is specific to the layer itself. If the position of the markers could be inside the child (layer's element) of the children (layers) the solution would be very easy. One could create a component wrapper for each layer, put additional logic there and return list of components with lat,lng position.

I don't see any neat solution to implement such scenario with the current library api. That requires having all layers' logic inside one component so that the components with lat,lng are rendered as a direct child :(

**Comment by wolasss** [comment]
Not to mention that if the marker is simply wrapped with HOC it won't work either

**Comment by itsmichaeldiego** [comment]
Mmm to be honest I can imagine many ways to do that, why not setting the wrapper on top of the GoogleMap instead? (If you really need _one_ wrapper to handle all of that? 

Also you could use a component where its wrapper its a Fragment, therefore you can set up all the logic you want, but then when rendered the Fragment will disappear and Markers will render.

Haven't tried any of those but there're many ways, its just about how to use React.

**Comment by jpmaligne** [comment]
Hello,
just wanted to answer to this as i'm facing the same problem and it is already the second issue closed I see on this topic.
I'm working with google-map-react on one hand and with react-leaflet on the other one, depending on if I want Google or Open Street Map as layer.

I am working with abstract marker components, polylines and so on, to make it work regardless of the library.
The fact that custom components must be direct children of the map component is forcing me to use the google-map API to display my markers... Which is not the killer feature of that lib, if I may say.

This lib is really good and helps me a lot, but I would be perfect if the map component could 'explorate' several levels of child components and make them render properly at good lat / lng.

To finish with, I don't think this is about how to use React but more about how to integrate google-map-react in various projects.

**Comment by shinonomeiro** [comment]
I agree with the OP and others who reported the same issue.

My current project requires me to put markers having the same coordinates into "cluster" markers (with a digit). I used to achieve that in a past project by wrapping the entire `entries.map(...)` into a `<Clusterizer>` parent component, which performed the grouping process transparently from the parent component. I was using the `react-google-maps` library at the time, which didn't have such restriction. Due to the lib not being maintained anymore, I had to switch to `google-map-react`. However, due to this present issue the above method isn't possible anymore, so I had to extract the grouping logic into a custom hook which basically achieves the same thing, then render the returned `clusters` object into <GoogleMap>.

Still, I would like to display a tooltip upon hovering on cluster markers, showing a list of entries from that group. My go-to library for tooltips/dropdowns in my current project is `tippyjs-react`, which requires me to wrap the marker with the provided `<Tippy>` component.

```tsx
<GoogleMap onGoogleApiLoaded={({ map }) => setMapInstance(map)}>
  {
    values(clusters).map(cluster => {
      const [i, entry] = head(cluster)!;

      return (
        cluster.length > 1 ? (
          <Dropdown
            key={entry.id}
            tippyProps={{
              placement: 'top',
              trigger: 'hover',
            }}
            content={onHide => (
              <DropdownSimpleMenu onClick={onHide}>
                // Omitted
              </DropdownSimpleMenu>
            )}
          >
            <Marker
              key={entry.id}
              lat={entry.location.lat}
              lng={entry.location.lng}
              active={index === i}
              isCluster={true}
              count={cluster.length}
            />
          </Dropdown>
        ) : (
          <Marker
            key={entry.id}
            lat={entry.location.lat}
            lng={entry.location.lng}
            active={index === i}
            onClick={() => onSelectEntry(i)}
          />
        )
      );
    })
  }
</GoogleMap>
```

Unfortunately this doesn't work, as for clusters the `Dropdown` component would become a direct child to `GoogleMap`.

**Comment by itsmichaeldiego** [comment]
You can wrap that into another component and render the Dropdown inside 😄

**Comment by itsmichaeldiego** [comment]
@shinonomeiro Can't you just wrap that into a component called, lets say `ClusteredMarker`? And pass the lat and lng to that component, and then you can render anything you need inside? Should work perfectly.

**Comment by MychaelZ** [comment]
This makes it difficult to write modular code. For instance,


```javascript
const SingleTrip = props => (
  <>
     <StartingMarker lat={props.startLat} lng={props.startLng} />
     <EndMarker lat={props.endLat} lng={props.endLng} />
     <RoutePolyline path={props.path} />
  </>
)

const MyTripMap = props => (
  <GoogleMapReact ...>
    <HomeMarker lat={10} lng={10} />
    <SingleTrip {...props.thatOneTrip} />
  </GoogleMapReact>
)

const AllMyTripMaps = props => (
  <GoogleMapReact ...>
    <HomeMarker lat={10} lng={10} />
    {props.trips.map(trip => (
      <SingleTrip key={trip.id} {...trip} />
    )))}
  </GoogleMapReact>
)
```

Must be written as:
```javascript
const SingleTrip = props => (
  <>
     <StartingMarker lat={props.startLat} lng={props.startLng} />
     <EndMarker lat={props.endLat} lng={props.endLng} />
     <RoutePolyline path={props.path} />
  </>
)

const MyTripMap = props => (
  <GoogleMapReact ...>
    <HomeMarker lat={10} lng={10} />
     <StartingMarker lat={props.thatOneTrip.startLat} lng={props.thatOneTrip.startLng} />
     <EndMarker lat={props.thatOneTrip.endLat} lng={props.thatOneTrip.endLng} />
     <RoutePolyline path={props.thatOneTrip.path} />
  </GoogleMapReact>
)

const AllMyTripMaps = props => (
  <GoogleMapReact ...>
    <HomeMarker lat={10} lng={10} />
    {props.trips.map(trip => (
     <StartingMarker key={`${trip.id}+start`} lat={trip.startLat} lng={trip.startLng} />
    )))}
    {props.trips.map(trip => (
     <EndMarker key={`${trip.id}+end`} lat={trip.endLat} lng={trip.endLng} />
    )))}
    {props.trips.map(trip => (
     <RoutePolyline key={`${trip.id}+poly`} path={trip.path} />
    )))}
  </GoogleMapReact>
)
```

Obviously this is a simple example but as a map because more complex this makes it difficult to maintain.

**Comment by discobean** [comment]
> Also you could use a component where its wrapper its a Fragment, therefore you can set up all the logic you want, but then when rendered the Fragment will disappear and Markers will render.

This is what would be expected, but wrapping a marker/component with a Fragment requires that the Fragment have the lat,lng properties.

**Comment by discobean** [comment]
I believe this should be re-opened because you cannot display 2 markers in a single loop function with different co-ordinates.

e.g. This does _not_ work as expected, all points just appear in the middle of the map:
```
{data.map((point, index) => {
<React.Fragment>
<MyPoint lat={point.one.lat} lng={point.one.lng} />
<MyPoint lat={point.two.lat} lng={point.two.lng} />
</React.Fragment>
})
```
