### ISSUE TITLE
Can't import fitBounds from google-map-react

### ISSUE THREAD

**Issue by Venskiy** [google-map-react/google-map-react#903]
I'm trying to update library to the newest release(2.0.4), but I can't import `fitBounds`. When I import `fitBounds` like this: `import { fitBounds } from 'google-map-react';`, webpack will show me this warning: `"export 'fitBounds' was not found in 'google-map-react'`

**Comment by itsmichaeldiego** [comment]
@Venskiy That is odd, I tried myself and it was working, would you please hold on the update till I can check that?

**Comment by Venskiy** [comment]
Thank you for helping.
I will also try to reproduce it on a clean project.

**Comment by itsmichaeldiego** [comment]
@Venskiy Yeah if you could share a live example with https://codesandbox.io/ or similar would be awesome, to see how are you using fitBounds and be able to test it properly

**Comment by Venskiy** [comment]
@itsmichaeldiego 
Here is sandbox example https://codesandbox.io/s/fast-glade-9kouq
I am able to import GoogleMap, but I can't import fitBounds. It's undefined.

**Comment by itsmichaeldiego** [comment]
@Venskiy Awesome, thanks, I will take a look as soon as I can

**Comment by fracmak** [comment]
Would this be part of the problem?

https://github.com/google-map-react/google-map-react/commit/1cae88eb5d8653a1913a0713dc3ce2dbf7214b85#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by karldanninger** [comment]
@fracmak that would be my guess as well! I'll try to PR a fix later today.

**Comment by itsmichaeldiego** [comment]
@fracmak Yes, indeed that is the problem, exporting the lib files that way resulted in an error with SSR. I rolled it back and checked and it seemed the others libs were being exported too, that was my bad, if @karldanninger doesn't fix it I will asap!

**Comment by karldanninger** [comment]
@itsmichaeldiego here https://github.com/google-map-react/google-map-react/pull/910

Exports all the utilities within the lib directory, including `fitBounds`

**Comment by adamklepacz** [comment]
./utils/helpers/mapHelpers.js
Attempted import error: 'fitBounds' is not exported from 'google-map-react'.

could you guys publish a fix to it?  And finally make it work. Every version from 2.0.0 broke my app so I needed to downgrade to the last stable release which was 1.1.7

**Comment by itsmichaeldiego** [comment]
@adamklepacz You are free to create your own PR, I'll approve it and merge it and release a new version 👍

**Comment by itsmichaeldiego** [comment]
I will take a look at this as soon as I've some spare time, stay tuned!

**Comment by michal-novacek** [comment]
first the typescript definition of fitBounds was broken in @types for 1.1.7, now it can't be imported in 2.x

i am trying to use this thing in production, please be more conservative in your testing and release strategy

**Comment by itsmichaeldiego** [comment]
@michal-novacek I think instead of complaining you should follow other people examples and try to help out, that is what open-source is about, we don't get paid to support your apps, its collaborative, not "complaintive". But I see you've no open-source contributions whatsoever, that means that you're one of those people who just use other peoples libraries without helping.

Besides that, if you want to use a library (any library) in production be careful on how you use your packages, as `2.x` is a major release, that means that has breaking changes, you should never update to major packages when in production unless testing them before, so please be more conservative in your testing and release strategy.

Going back to the issue, we're working together with people to fix it, feel free to check #923 and the conversation there, so you can learn more about what's going on, you'll see that its not our problem but an issue with microbundle, that we're trying to fix together with @NerdCowboy and @karldanninger

**Comment by itsmichaeldiego** [comment]
This was fixed and released in 2.1.3, please let me know if it works!! 🙏

**Comment by rekomat** [comment]
It does! Thanks for the patch! 💪
