### ISSUE TITLE
GoogleMapReact refuses to appear as a functional component.

### ISSUE THREAD

**Issue by Brystephor** [google-map-react/google-map-react#908]
**Describe the bug 🐛**

I am attempting to render the `SimpleMap` component as a functional component rather than using the component class.

**To Reproduce 🔍**

Convert the given `SimpleMap` class component to a functional react component and it will not work.

Here's a codesand box of the differences:
https://codesandbox.io/s/zen-kalam-75527?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior 💭**

I expect the functional component to act in the exact same manner as the class component. For this particular issue, the map should still appear.

**Environment:**

 - OS:windows 10
 - chrome

**Additional context**

This is using`google-map-react`  v2.0.4 with `react` v16.3.1

**Comment by itsmichaeldiego** [comment]
@Brystephor Your issue is not with the library, but with a wrong usage of JS and object destructuring. 

Check in your code, you're using destructuring assignment syntax in the `props by doing: `{ center, zoom, ...props }`, that means that `center` and `zoom` are now destructured from props. Therefore they won't be accesible through `props.center` or `props.zoom` as you're trying to do:

```javascript
function SimpleMapFunction({
  center = {
    lat: 47.6062,
    lng: 122.3321
  },
  zoom = 11,
  ...props
}) (
    <GoogleMapReact
      bootstrapURLKeys={{ key: "YOUR_KEY" }}
      defaultCenter={props.center} <= undefined
      defaultZoom={props.zoom} <= undefined
    />
);
```

Instead you should do:
```javascript
    <GoogleMapReact
      bootstrapURLKeys={{ key: "YOUR_KEY" }}
      defaultCenter={center}
      defaultZoom={zoom}
    />
);
```

And voi·la! It works.

Feel free to check the following codesandbox: 
https://codesandbox.io/s/summer-haze-xkp19?file=/src/MapFunctional.js

Please be more mindful when opening issues in a library, it takes time and effort from us 👍 

Take a look at [mozilla's documentation about Destructuring assigment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

**Comment by luizgt** [comment]
I was facing the same problem, thans @itsmichaeldiego for this help!!! 👏🏻
