### ISSUE TITLE
How to show places suggestions list on the top? 

### ISSUE THREAD

**Issue by lossen** [google-map-react/google-map-react#927]
I would like to show place suggestions list on the top side because in design I have location input at the bottom of the screen. When I type some place and suggestions are open, the size of the screen increases because suggestions don't fit in screen height.  Can I do that? Or maybe limit the height of suggestions list or any other solution to this problem. 
 
1. Place input at the bottom of the screen
2. Type location

GIF example
![ezgif-7-568d894a5abc](https://user-images.githubusercontent.com/14949813/91419167-e986d700-e874-11ea-8eba-1508fd2c7423.gif)

**Environment:**

 - OS: mac Catalina 10.15.6
 - Chrome 84
 - google-map-react: 1.1.7

**Comment by itsmichaeldiego** [comment]
MM Wouldn't go for limiting the height because that is not the problem. 

I think you should use CSS here, like some type of position absolute, that way the page content won't expand. I would need to see the whole code to point out a proper solution, but I can think of different ways. Also you could move it to the top, but I am guessing you want it there.

**Comment by itsmichaeldiego** [comment]
Please if you're still facing this issue open a new one with a live code example, thanks!
