### ISSUE TITLE
onChange: get all markers that are visible within bounds

### ISSUE THREAD

**Issue by dsc-topher** [google-map-react/google-map-react#941]
I am not sure if I missed it somewhere on the API documentation but I don't have much idea on how to get the map object and use `map.getBounds().contains(LatLng)` during `onChange `event. I need to filter an external component based on what markers are visible on the map so I need to know which child markers are visible. 

Thanks

**Comment by itsmichaeldiego** [comment]
@dsc-topher Hey, I think you could find all the info you need by browsing the issues instead of opening a new one! 

Here is the info on how to access the `map` and `maps` object: https://github.com/google-map-react/google-map-react#use-google-maps-api

And if you need to use `map` outside of that function, you can just set a reference to it! 

Let us know if you've more questions, but im closing this as its not an issue.

**Comment by dsc-topher** [comment]
Thank you.
