### ISSUE TITLE
Keyboard navigation for markers on map

### ISSUE THREAD

**Issue by mathiasha** [google-map-react/google-map-react#943]
I have an implementation of the maps on a site. We are trying to make some accessibility improvements, and have noticed that markers are not keyboard accessible.

I need to be able to tab to the markers, and interact with them.

**Comment by karldanninger** [comment]
Hey, because markers are all React components, you should write your accessibility directives onto those marker components you create.

There are many resources online on how this can be done. Just treat your markers as any other react component you build in your application.

I hope this helps you.
